services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_brasil_local_django
    container_name: django_brasil_local_django
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: /start
